language: python

python:
  - "2.7"
  - "3.6"

cache:
  - apt
  - pip

addons:
  apt:
    packages:
    - python-dev

before_install:
  - "travis_retry pip install --upgrade pip"

install:
  - "travis_retry pip install --upgrade -r requirements.txt"

script:
  - python setup.py install
  - pytest testsuite

after_success:
  - coveralls

sudo: false