language: python

python:
  - "2.7"

cache:
  - apt
  - pip

addons:
  apt:
    packages:
    - python-dev

before_install:
  - "travis_retry pip install --upgrade pip"

install:
  - python setup.py install
  - py.test testsuite
  - "travis_retry pip install -r requirements.txt"

script:
  - "coverage report --source=hepdata_validator setup.py test"

after_success:
  - coveralls

sudo: false